# Meta Data for SEO

## Homepage
title = "API Network"
titleSeparator = "-"
titleAddition = "Distributed API Information"
description = "API Network provides resources regarding your distributed API that allows you to understand how it is accessible across the globe."

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "henkverlinde"
twitterCreator = "henkverlinde"
facebookAuthor = "verlinde.henk"
facebookPublisher = "verlinde.henk"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/Art_Wolf"
schemaLinkedIn = "https://www.linkedin.com/in/johncolmdoyle/"
schemaGitHub = "https://github.com/johncolmdoyle"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = true
alertText = "Like API Network? <a class=\"alert-link\" href=\"https://github.com/johncolmdoyle/postman-hackathon/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/johncolmdoyle/postman-hackathon-website"
editPage = false
